#hkp://keyserver.ubuntu.com:80

- name: add mongo (key)
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 0C49F3730359A14518585931BC711F9BA15703C6

- name: add mongo deb
  apt_repository:
      repo: deb [ arch=amd64 ] http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 multiverse
      state: present
      filename: 'mongodb-org-3.4'

- name: install mongo
  apt: name=mongodb-org state=present

- name: install php5-mongo
  apt: name=php5-mongo state=present
  notify:
    - reload apache