- hosts: all
  sudo: true
  tasks:
    - name: update apt cache
      apt: update_cache=yes
  roles:
    - curl
    - git
    - apache
    - mysql
    - php
    - php5-cli
    - php5-dev
    - node
    - yarn
    - mongodb
    - rabbitmq
