

- name: add rabbitmq (key)
  apt_key:
      url: "https://www.rabbitmq.com/rabbitmq-release-signing-key.asc"
      state: present

- name: add rabbitmq deb
  apt_repository:
      repo: deb http://www.rabbitmq.com/debian/ testing main
      state: present
      filename: 'rabbitmq'

- name: install rabbitmq
  apt: name=rabbitmq-server state=present
  notify:
    - reload apache